### ISSUE TITLE
Lacking requirements.txt

### ISSUE THREAD

**Issue by terciodemelo** [czheo/syntax_sugar_python#10]
Should we have a `requirements.txt` for virtualenv usage?

**Comment by czheo** [comment]
I think `pip install -e .` is enough for development

**Comment by czheo** [comment]
Just added `CONTRIBUTING.md`. https://github.com/czheo/syntax_sugar_python/blob/master/CONTRIBUTING.md
So people can follow the steps here to setup the development env.
